### ISSUE TITLE
Planting does not decrease seed count

### ISSUE THREAD

**Issue by exot** [tenplus1/farming#32] opened 2017-11-05 09:42 UTC
Hi,

when using the most recent version of the farming mod (ce0c3e8), planting wheat (and indeed also other plants like chili or cocoa) does not decrease the seed count: after sowing, the number of seeds is the same as before.  I could track down this behavior to commit df1aa7f, before that everything works as expected; however, I cannot see how this commit introduces this error :(

Version of Minetest is 0.4.16, Debian version 0.4.16+repack-2~bpo9+1,

Any ideas?

Thanks!

  Daniel

**Comment by groenkek** [comment] 2018-01-03 10:02
Cannot reproduce, could you please elaborate on whether it still persists?

**Comment by tenplus1** [comment] 2018-01-04 09:35
you either have creative mode active or have 'creative' privelage in survival. closing issue.

**Closed by tenplus1** 2018-01-04 09:35 UTC
